#pragma once

#include "driver/gpio.h"

#define TRAFFIC_LIGHT_GREEN_GPIO       GPIO_NUM_5
#define TRAFFIC_LIGHT_YELLOW_GPIO      GPIO_NUM_4
#define TRAFFIC_LIGHT_RED_GPIO         GPIO_NUM_7

#define TRAFFIC_LIGHT_RED_US           10000000ULL
#define TRAFFIC_LIGHT_RED_YELLOW_US     2000000ULL
#define TRAFFIC_LIGHT_GREEN_US         10000000ULL
#define TRAFFIC_LIGHT_GREEN_BLINK_US    3000000ULL
#define TRAFFIC_LIGHT_YELLOW_US         3000000ULL
#define TRAFFIC_LIGHT_YELLOW_BLINK_US   3000000ULL

#define TRAFFIC_LIGHT_BLINK_US          500000ULL

#define BUTTON_GPIO                     GPIO_NUM_10
#define BUTTON_DEBOUNCE_US              50000ULL
#define BUTTON_LONG_PRESS_US            2000000ULL